### ISSUE TITLE
not working on garena server

### ISSUE THREAD

**Issue by luong232** [Kyrluckechuck/TFT-Bot#37] opened 2022-12-10 06:22 UTC
when i start the bot,it close the game and got error,i try 3 times but it still close the game and error

**Comment by Kyrluckechuck** [comment] 2022-12-10 06:28
Can you provide any information or context to this? Could you attach the log file the bot created?

**Comment by Kyrluckechuck** [comment] 2022-12-10 06:29
Though it's also worth noting that you mention this is the Garena server, and while I'll try to provide basic support I do not plan to go largely out of my way to support that client since it will be discontinued this year (since it's merging to "League proper"), on top of it not being accessible to me

**Comment by luong232** [comment] 2022-12-10 06:49
> Though it's also worth noting that you mention this is the Garena server, and while I'll try to provide basic support I do not plan to go largely out of my way to support that client since it will be discontinued this year (since it's merging to "League proper"), on top of it not being accessible to me

do u have any social media like twitter or telegram ? i will send you the clip that will explain my problem,my english is very bad so i cant provide the problem i got,sorry.

**Comment by Kyrluckechuck** [comment] 2022-12-10 06:54
I would prefer to keep it to the project. If you could attach the log file at `%APPDATA%/TFT Bot/tft.log` or `%APPDATA%/TFT Bot/TFT Bot.log`, that would be helpful.

By the initial description, it sounds like this may be a duplicate of https://github.com/Kyrluckechuck/TFT-Bot/issues/35, which was resolved with the [v0.9.5](https://github.com/Kyrluckechuck/TFT-Bot/releases/tag/main-5b159fe6) release.

**Comment by Kousuke-kun** [comment] 2022-12-10 07:41
I have the same issue, also Garena.
[TFT.Bot.log](https://github.com/Kyrluckechuck/TFT-Bot/files/10199448/TFT.Bot.log)

**Comment by luong232** [comment] 2022-12-10 11:53
hi,sorry for late reply,this is my log 
[TFT.Bot.log](https://github.com/Kyrluckechuck/TFT-Bot/files/10200004/TFT.Bot.log)

**Comment by Kousuke-kun** [comment] 2022-12-11 02:12
I'm unable to find the registry key for the Garena install location, I'm assuming it's because the Garena client has you choose the install location?

Anyway, the path for my install is at here
![explorer_n8A0o24HBU](https://user-images.githubusercontent.com/34085679/206883190-96c1fc7b-0678-4f5d-b484-f3d57a790247.png)

The parent folder (C:\Riot Games\League of Legends) was something I created myself though, so that would make the "*/32771" part the install location?

**Comment by Kyrluckechuck** [comment] 2022-12-11 21:37
A interesting that you must specify the install location which makes that more difficult to automate.

I suppose at the very least, I could make it so the League install folder is configured via the `bot_settings.ini` config 🤔

**Closed** 2022-12-11 22:54 UTC
Labels: bug, enhancement

**Comment by Kyrluckechuck** [comment] 2022-12-11 22:56
I have implemented this via the new setting in `bot_settings.ini`, which according to the screenshot you included, I think that would be:
```
[SETTINGS]
OverrideInstallLocation = C:\Riot Games\League of Legends\32771
```
